version: "3.3"

services:
    nginx:
        build: ./nginx/
        ports:
            - 8888:80
            - 443:443
        volumes:
            - ./:/var/www/html:ro
            - ./nginx/vhosts:/etc/nginx/conf.d/:ro
        networks:
            - server

volumes:
    data:
networks:
    database:
    server:
    ansible:
